name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Code linting
    uses: lexmag/elixir-actions/.github/workflows/lint.yml@v2
    with:
      otp-version: "24"
      elixir-version: "1.14"

  test:
    name: Test suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["25", "26"]
        elixir: ["1.14", "1.15", "1.16", "1.17", "1.18"]
        runtime_config: [true, false]

        include:
          # OTP 27 works with Elixir 1.17.0+
          - otp: "27"
            elixir: "1.17"
            runtime_config: true
          - otp: "27" 
            elixir: "1.17"
            runtime_config: false
          - otp: "27"
            elixir: "1.18"
            runtime_config: true
          - otp: "27"
            elixir: "1.18"
            runtime_config: false

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test
        env:
          STATIX_TEST_RUNTIME_CONFIG: ${{ matrix.runtime_config }}